//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTAWebService.OTAWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OTAWebServiceRef.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProducts(string merchantCode, string parameters, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderOccupies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OrderOccupies(string merchantCode, string postOrder, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testSignture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string testSignture(string merchantCode, string parames, string parames1, string parmes2, string parmes3, string merchantKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOrderEdit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangeOrderEdit(string merchantCode, string postOrder, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllOrderStatus(string merchantCode, string postOrder, string signature, string BusinessType, string parkCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testOrderOccupiesJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string testOrderOccupiesJson(string merchantCode, string date, string mkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuotaInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetQuotaInfo(string parkCode, string otaCode, string date, string parameters, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderFinish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OrderFinish(string otaCode, string otaOrderNO, int platformSend, string parameters, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OrderRelease(string otaCode, string otaOrderNO, string parameters, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAccountInfo(string merchantCode, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RepeatMess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RepeatMess(string merchantCode, string signature, int parkSend, string conditions, string postOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : OTAWebService.OTAWebServiceRef.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<OTAWebService.OTAWebServiceRef.ServiceSoap>, OTAWebService.OTAWebServiceRef.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetProducts(string merchantCode, string parameters, string signature) {
            return base.Channel.GetProducts(merchantCode, parameters, signature);
        }
        
        public string OrderOccupies(string merchantCode, string postOrder, string signature) {
            return base.Channel.OrderOccupies(merchantCode, postOrder, signature);
        }
        
        public string testSignture(string merchantCode, string parames, string parames1, string parmes2, string parmes3, string merchantKey) {
            return base.Channel.testSignture(merchantCode, parames, parames1, parmes2, parmes3, merchantKey);
        }
        
        public string ChangeOrderEdit(string merchantCode, string postOrder, string signature) {
            return base.Channel.ChangeOrderEdit(merchantCode, postOrder, signature);
        }
        
        public string GetAllOrderStatus(string merchantCode, string postOrder, string signature, string BusinessType, string parkCode) {
            return base.Channel.GetAllOrderStatus(merchantCode, postOrder, signature, BusinessType, parkCode);
        }
        
        public string testOrderOccupiesJson(string merchantCode, string date, string mkey) {
            return base.Channel.testOrderOccupiesJson(merchantCode, date, mkey);
        }
        
        public string GetQuotaInfo(string parkCode, string otaCode, string date, string parameters, string signature) {
            return base.Channel.GetQuotaInfo(parkCode, otaCode, date, parameters, signature);
        }
        
        public string OrderFinish(string otaCode, string otaOrderNO, int platformSend, string parameters, string signature) {
            return base.Channel.OrderFinish(otaCode, otaOrderNO, platformSend, parameters, signature);
        }
        
        public string OrderRelease(string otaCode, string otaOrderNO, string parameters, string signature) {
            return base.Channel.OrderRelease(otaCode, otaOrderNO, parameters, signature);
        }
        
        public string GetAccountInfo(string merchantCode, string signature) {
            return base.Channel.GetAccountInfo(merchantCode, signature);
        }
        
        public string RepeatMess(string merchantCode, string signature, int parkSend, string conditions, string postOrder) {
            return base.Channel.RepeatMess(merchantCode, signature, parkSend, conditions, postOrder);
        }
    }
}
