// <auto-generated />
namespace WeiXinPF.Infrastructure.DomainDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Photo4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Photo4));
        
        string IMigrationMetadata.Id
        {
            get { return "201509140201089_Photo4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
